name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name foodlytics

      - name: Build and Push Docker Image
        run: |
          docker build -t foodlytics-eqbaanavawbqcxfs.azurecr.io/backend:latest ./backend
          docker push foodlytics-eqbaanavawbqcxfs.azurecr.io/backend:latest

      - name: Deploy to Azure App Service
        run: |
          # Enable admin user if not already enabled to get credentials
          az acr update -n foodlytics --admin-enabled true
          
          # Retrieve ACR credentials
          ACR_USERNAME=$(az acr credential show --name foodlytics --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name foodlytics --query "passwords[0].value" -o tsv)
          
          az webapp config container set \
            --name foodlytics-backend \
            --resource-group rg-foodlytics \
            --docker-custom-image-name foodlytics-eqbaanavawbqcxfs.azurecr.io/backend:latest \
            --docker-registry-server-url https://foodlytics-eqbaanavawbqcxfs.azurecr.io \
            --docker-registry-server-user $ACR_USERNAME \
            --docker-registry-server-password $ACR_PASSWORD
